apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app-umbrella-chart.fullname" . }}-config
  labels:
    {{- include "app-umbrella-chart.labels" . | nindent 4 }}
data:
  API_BASE_URL: {{ .Values.app.config.API_BASE_URL | quote }}
  LOG_LEVEL: {{ .Values.app.config.LOG_LEVEL | quote }}
  MAX_CONNECTIONS: {{ .Values.app.config.MAX_CONNECTIONS | quote }}